### PR TITLE
Fix #145: cli parsing - handle correctly false value for validator

### LINKED ISSUE #145: Bug: CLI Argument parsing typos invokes other validates
## Expected Behavior

Not to validate the integrity by default via CLI command
e.g.) 
```
npx lockfile-lint --validate-https -validate-package-names --validate-integrity --path yarn.lock
```

## Current Behavior

```
npx lockfile-lint --validate-https -validate-package-names --validate-integrity false --path yarn.lock
```
Always seems to validate the integrity is sha512

## Steps to Reproduce (for bugs)

1. Run `npx lockfile-lint --validate-https -validate-package-names --validate-integrity --path yarn.lock`
with a lockfile that is using sha1 integrity
image

Have also tried passing false as an aargument to `--validate-integrity` which also did not work

## Your Environment

- Library Version used: 4.9.5
- Node.js version (e.g. Node.js 5.4): 16
- Operating System and version (desktop or mobile): MacOS 12.6

### PR DESCRIPTION
**Pull request by yoavain**
## Description
When adding a validator boolean flag to command line, the value was ignored, and the validator was activated even if its value was "false".

## Types of changes
* Fixed some CLI tests failing on Windows with "Error: spawn UNKNOWN" due to running with `childProcess.spawn(cliExecPath, [...])`. Changed to `childProcess.spawn('node', [cliExecPath, ...])`
* Added validator only if commandValue is not falsy 
* Added tests to make sure validator does not run when flag is missing, or flag is set to "false"
* Added another cli test for the integrity validator

>**Note:** This does not resolve command-line with typos.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue
https://github.com/lirantal/lockfile-lint/issues/145

## Checklist:

- [ ] I have updated the documentation (if required).
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
Thanks @yoavain 👏

Overall looks ok, but I was wondering if this won't cause an issue with the `--empty-hostname` validator which on falsy value actually enables a stricter check? I'll check the code really quickly myself too but wanted to float that before merging.

**Comment by lirantal** [comment]
Anyway, looks ok to me to merge but let me know if you think otherwise.

**Comment by yoavain** [comment]
@lirantal 
I think the change only affects the flags in `supportedValidators`. `empty-hostname` is not in that map

**Comment by lirantal** [comment]
You're right, I see it passed in later as the option to the validators.
Let's land it then.

**Pull request merged**
