### PR TITLE
feat(schema): support protocol schema and refactor host validators

### PR DESCRIPTION
**Pull request by lirantal**
## Description

- Refactor current behavior of --allowed-hosts to actually use just the hostname instead of a full URL
- Introduces a protocol schema support to allow specifying protocols such as `https:` `git+ssh:` etc

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Addresses issues brought up in #11 

## Motivation and Context

#11 brought up interesting idea in terms of supporting protocols

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
cc @nottoseethesun you might want to take a look

**Comment by nottoseethesun** [comment]
I can't try this out, because there's no way to run the program.

If I try to install locally, I get `Error: Cannot find module 'lockfile-lint-api'`.  There's no link in `node_modules/.bin`, and so I have to go into the actual package.

If I try to install globally or use npx, which I prefer to not do, then I get `-bash: lockfile-lint: command not found` or `lockfile-lint: command not found`.

**Comment by nottoseethesun** [comment]
Otherwise, lgtm, with the caveat that hopefully a few of the rest of the uri components could be supported soon, so that if a user wants to allow an npm package from github.com, they can limit it much more than all of github.   The most frequent use of `git+ssh` or `git+https` would occur though with intranet git installations, so in that case, a hostname of `github.foo.bar` would suffice, which appears to be supported here.

**Comment by lirantal** [comment]
@nottoseethesun yes, a bit tricky to get this tested on a local install with monorepo setup. Hopefully will have time later on to explain this out in the docs.

Thanks, appreciate the input!

**Pull request merged**
