### PR TITLE
feat: provide the actual bad string in ValidateScheme

### PR DESCRIPTION
**Pull request by pratik97**
## Description

In ValidateScheme providing the actual scheme string against which we validate.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

Added/Updated unit tests.

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun
funnycat

### CODE REVIEW

**Comment by lirantal** [comment]
@pratik97 a few issues here we should fix.

I think the output would be a bit hard to read, especially when we apply the same to hosts, etc.
With this PR it looks like this:

```
detected invalid scheme(s) https: for package: @babel/code-frame@^7.0.0
error: command failed with exit code 1
```

the invalid string in the lockfile is "http", which is wrongly showing here as "https" but regardless, it is too blended. How about we format it something like this as an output:

```
detected invalid scheme(s) for package: @babel/code-frame@^7.0.0
  -> http:
error: command failed with exit code 1
```

Do you think that's clear for a user?

The other issue is that the current code in this PR logs the allowed scheme, while we want to print out the bad one that is written in the lockfile and doesn't comply with the policy.

**Comment by lirantal** [comment]
another thought about how to print out the bad values is to maybe use an assertion style, something like this:

```
detected invalid scheme(s) for package: @babel/code-frame@^7.0.0
  expected: https:
  found: git+https
error: command failed with exit code 1
```

**Comment by lirantal** [comment]
@pratik97 great work here.

before we merge, can we:
1. apply the same error formatting to the other flags too? I don't want to merge this in stages because then the errors will be inconsistent in their print-out.
2. can you make the last line about the error `error: command failed with exit code 1` to have a newline break?

**Comment by pratik97** [comment]
@lirantal I will work on it this weekend. Sorry, for the late reply :/

**Comment by lirantal** [comment]
@pratik97 sure

**Comment by lirantal** [comment]
@pratik97 thanks for pushing the commits, looks like you addressed all valdiators, or is there something still to be addressed in this PR?

**Comment by pratik97** [comment]
@lirantal no, I am done :)

**Comment by lirantal** [comment]
ok thanks, I shared on twitter a screenshot to get some feedback before we merge: https://twitter.com/liran_tal/status/1190655364758421507?s=20

One of which is to change `found` to `actual` which I agree with.

**Comment by lirantal** [comment]
@pratik97 let's add that change and I'll merge as a new major version.
we'll follow it up with other changes as they come by

**Comment by pratik97** [comment]
@lirantal done!

**Comment by lirantal** [comment]
Great stuff @pratik97, thanks for pushing this! ✨💪

**Comment by lirantal** [comment]
fixes #10

**Pull request merged**
