### PR TITLE
feat: add validation success console message

### LINKED ISSUE #76: Add "all is good" confirmation when validation succeeds
**Is your feature request related to a problem? Please describe.**
Currently when you run the validation command and everything succeed you don't get any feedback in the console so it leaves you wondering if validation actually took place.

**Describe the solution you'd like**
Add some some sort of confirmation message like `👍 Validation successful` if everything passed.

### PR DESCRIPTION
**Pull request by bolatovumar**
Adds validation success message.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Close #76

## Motivation and Context

Informs the user that everything is good so the user is not left wondering if the validation actually ran successfully.

## How Has This Been Tested?

Manually

## Screenshots (if appropriate):

Screen Shot 2020-03-28 at 4 05 51 PM

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Good stuff, thanks @bolatovumar

**Comment by XhmikosR** [comment]
FYI the emojis don't work on Windows default cmd @lirantal

**Comment by lirantal** [comment]
Thanks @XhmikosR. what does it look like?

**Comment by XhmikosR** [comment]
ll

**Comment by lirantal** [comment]
Gotcha.
Feel like PRing a small one to remove the emoji?

**Pull request merged**
