### PR TITLE
chore(deps): update @commitlint/cli to v7.3.5

### PR DESCRIPTION
**Pull request by XhmikosR**
This fixes 14/15 npm audit issues

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation (if required).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

---

I left any other deps updates, but there are still plenty of npm audit issues in the sub-packages

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oops this must fail because I missed updating yarn.lock since I don't use yarn.

**Comment by XhmikosR** [comment]
Should be OK now.

**Comment by XhmikosR** [comment]
@lirantal we can drop this one if you plan to update the deps yourself later. I just noticed it when initially did `npm i`.

**Comment by lirantal** [comment]
That's my plan but leaving open until I get to it so it doesn't slip the radar :-)

**Comment by XhmikosR** [comment]
@lirantal I'm gonna close this since it's obsolete AFAICT . Regardless, there are more vulnerabilities to fix now :)

**Comment by lirantal** [comment]
Cool thanks for watching over this ❤️🙏

**Pull request closed without merging**
