### PR TITLE
Remove emoji from output

### PR DESCRIPTION
**Pull request by XhmikosR**
@lirantal there you go :) We could get fancy and check for Windows, but it's your call for another time.

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks buddy! 🤗

About the Windows support - were you thinking about just detecting the OS and based on that, or did you have in mind some kind of terminal support detection?

**Comment by XhmikosR** [comment]
Just `process.platform`.

**Comment by lirantal** [comment]
Ok. I was interested because I saw that there's no easy way to detect character and emoji support in terminals.

**Comment by XhmikosR** [comment]
Yeah, that's why I said "it's your call for another time" 😛

**Comment by lirantal** [comment]
Cool :)

**Pull request merged**
