### PR TITLE
fix: package names from github

### PR DESCRIPTION
**Pull request by tian000**
## Description

Some packages come from directly github - these packages fail the validate package name check

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?
Unit tested

## Checklist:

- [ ] I have updated the documentation (if required).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks for bringing this up @tian000 

A concern I have is that if we merge this pull request then it essentially allows attackers to bypass it because to satisfy the logic the matches `https://github.com/Bundlr-Network/avsc#a730cc8018b79e114b6a3381bbb57760a24c6cef'` I can just create my own user/org name instead of `Bundlr-Network` and spoof the source. Correct?

**Comment by tian000** [comment]
> Thanks for bringing this up @tian000
> 
> A concern I have is that if we merge this pull request then it essentially allows attackers to bypass it because to satisfy the logic the matches `https://github.com/Bundlr-Network/avsc#a730cc8018b79e114b6a3381bbb57760a24c6cef'` I can just create my own user/org name instead of `Bundlr-Network` and spoof the source. Correct?

Yes that is correct. However, if you are able to compromise the host you can spoof a package regardless. Do you recommend that I just disable the --validatePackageNames check?

**Comment by lirantal** [comment]
Not exactly though because the package name is checked to match between the one actually used in the dependency and the one used in the sourced URL. The only occurrence of the `--validPackageNames` check not being helpful is if you also don't enforce a registry source.

**Comment by lirantal** [comment]
I'm re-reading this and not confident there's a clear decision to make here. I'll close for now but if you still want to raise this as a significant requirement and can add more context and reference use-cases I'm happy to re-consider.

**Pull request closed without merging**
