### PR TITLE
readme: add link to debug package

### PR DESCRIPTION
**Pull request by glensc**
Currently there's nothing documented how to tune verbose output.

Reading source code, seems the `DEBUG` variable comes from [debug] node package.

So at least add link to that package.

[debug]: https://www.npmjs.com/package/debug

### CODE REVIEW

**Comment by lirantal** [comment]
thanks @glensc for chiming in and sending this PR ❤️
what value do you see in specifying the debug package in the README? why would someone care which package is being used?

**Comment by glensc** [comment]
well, there's no information what I can customize in the debugging, so at least linking to the package I can get info on how to drive the DEBUG variable.

altho I'd prefer if the debugging could be controlled via command line argument, it's more standard and convenient to use than envirohment variables.

and the tool should print more info by default, having no output can be confusing, like, did the program even run?

**Comment by lirantal** [comment]
I would like to avoid naming dependencies because that is an implementation detail.
Initially you said this:

> Currently there's nothing documented how to tune verbose output.

How did you end up tuning it?
As in, what did you do that was different than the original `DEBUG=*` recommendation specified in the current README?

With regards to the second part of your last comment:

> altho I'd prefer if the debugging could be controlled via command line argument, it's more standard and convenient to use than envirohment variables.
> and the tool should print more info by default, having no output can be confusing, like, did the program even run?

These sound like good ideas for a PR so I'm happy to receive and merge one if you wanted to work on it. Specifically on the last one, not sure what you'd like to see as "print more info by default" but I'm happy to discuss.

**Comment by lirantal** [comment]
Will close for now but happy to re-open if there's more to it.

**Pull request closed without merging**
